name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Grant execute permission
        run: chmod +x SeasonCode2025/gradlew
      - name: Fix Formatting
        working-directory: SeasonCode2025
        run: ./gradlew :spotlessApply
      - name: Check formatting
        working-directory: SeasonCode2025
        run: ./gradlew spotlessCheck
      - name: Build robot code
        working-directory: SeasonCode2025
        run: ./gradlew build
